# Generated by Django 4.2.1 on 2023-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truthlist', '0005_category_question_reason_reasonanswer_useranswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='add_to_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=10),
        ),
    ]
