# Generated by Django 4.2.1 on 2023-06-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truthlist', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
